# Generated by Django 5.2.8 on 2025-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrszagElemzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valtozo_neve', models.CharField(max_length=100)),
                ('valtozo_teljes_neve', models.CharField(max_length=100)),
                ('f_ertek', models.FloatField(null=True)),
                ('p_ertek', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegioElemzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valtozo_neve', models.CharField(max_length=100)),
                ('valtozo_teljes_neve', models.CharField(max_length=100)),
                ('f_ertek', models.FloatField(null=True)),
                ('p_ertek', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
