# Generated by Django 5.2.8 on 2025-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalityTestCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('sw_w', models.FloatField(blank=True, null=True)),
                ('sw_p', models.CharField(blank=True, max_length=20, null=True)),
                ('ks_d', models.FloatField(blank=True, null=True)),
                ('ks_p', models.CharField(blank=True, max_length=20, null=True)),
                ('cvm_w_sq', models.FloatField(blank=True, null=True)),
                ('cvm_p', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_a_sq', models.FloatField(blank=True, null=True)),
                ('ad_p', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrszagElemzes',
        ),
        migrations.DeleteModel(
            name='RegioElemzes',
        ),
    ]
