# Generated by Django 5.2.8 on 2025-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_normalitytestcountry_delete_orszagelemzes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnovaTestCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('anova_F', models.FloatField(blank=True, null=True)),
                ('anova_p', models.CharField(blank=True, max_length=20, null=True)),
                ('levene_F', models.FloatField(blank=True, null=True)),
                ('levene_p', models.CharField(blank=True, max_length=20, null=True)),
                ('welch_F', models.FloatField(blank=True, null=True)),
                ('welch_p', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
