# Generated by Django 5.2.8 on 2025-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_anovatestcountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anovatestcountry',
            old_name='anova_F',
            new_name='f_value',
        ),
        migrations.RenameField(
            model_name='anovatestcountry',
            old_name='anova_p',
            new_name='p_value',
        ),
        migrations.RemoveField(
            model_name='anovatestcountry',
            name='levene_F',
        ),
        migrations.RemoveField(
            model_name='anovatestcountry',
            name='levene_p',
        ),
        migrations.RemoveField(
            model_name='anovatestcountry',
            name='welch_F',
        ),
        migrations.RemoveField(
            model_name='anovatestcountry',
            name='welch_p',
        ),
        migrations.AlterField(
            model_name='anovatestcountry',
            name='variable',
            field=models.CharField(max_length=200),
        ),
    ]
