# Generated by Django 5.2.8 on 2025-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_anova_f_anovatestcountry_f_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalityTestRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('sw_w', models.FloatField(blank=True, null=True)),
                ('sw_p', models.CharField(blank=True, max_length=20, null=True)),
                ('ks_d', models.FloatField(blank=True, null=True)),
                ('ks_p', models.CharField(blank=True, max_length=20, null=True)),
                ('cvm_w_sq', models.FloatField(blank=True, null=True)),
                ('cvm_p', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_a_sq', models.FloatField(blank=True, null=True)),
                ('ad_p', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
