# Generated by Django 5.2.8 on 2025-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_normalitytestregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnovaTestRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=200)),
                ('f_value', models.FloatField(blank=True, null=True)),
                ('p_value', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
