# Generated by Django 5.2.8 on 2025-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_anovatestregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anovatestregion',
            old_name='f_value',
            new_name='anova_f',
        ),
        migrations.RenameField(
            model_name='anovatestregion',
            old_name='p_value',
            new_name='anova_p',
        ),
        migrations.AddField(
            model_name='anovatestregion',
            name='levene_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anovatestregion',
            name='levene_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anovatestregion',
            name='welch_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anovatestregion',
            name='welch_p',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
