# Generated by Django 5.2.8 on 2025-12-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_f_value_anovatestregion_anova_f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anovatestregion',
            name='welch_f',
        ),
        migrations.RemoveField(
            model_name='anovatestregion',
            name='welch_p',
        ),
    ]
