# Generated by Django 5.2.8 on 2025-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_anovatestregion_welch_f_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anovatestcountry',
            old_name='f_value',
            new_name='anova_f',
        ),
        migrations.RenameField(
            model_name='anovatestcountry',
            old_name='p_value',
            new_name='anova_p',
        ),
        migrations.AddField(
            model_name='anovatestcountry',
            name='levene_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anovatestcountry',
            name='levene_p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
